### ISSUE TITLE
Server maintenance 18.07.2024

### ISSUE THREAD

**Issue by aparcar** [openwrt/asu#663]
For whatever reason the server is acting up as in not propagating the right versions. I'm investing please wait before reporting any issues.

**Comment by aparcar** [comment]
Good old `podman system reset --force` fixed the issues, for some reason the containers DNS resolution wouldn't work anymore.

**Comment by aparcar** [comment]
A new round, I'll have to reconfigure multiple things, server is down until further notice, should be done by tomorrow.

Sorry for the inconvenience

**Comment by hardcorp74** [comment]
> Any progress? firmware selector still down
I try build - it works, but cann't download files with compiled fw...

**Comment by fsa** [comment]
Unfortunate coincidence. I need to update urgently, as there is a bug in firmware 23.05.3 and my NAT64 is not working and the update is not available.

**Comment by jalexvig** [comment]
Looks like builds are now working but not downloads

**Comment by aparcar** [comment]
I tested firmware selector, AUC and OWUT, all working as expected. Docker lagging issues may appear due to our CI being bloated with kernel builds, that's another mission for another day.

**Comment by jalexvig** [comment]
@aparcar Would this cause the 404s seen on download links?

**Comment by jalexvig** [comment]
Ah looks like it's just cached build download links that 404 - I just added an extra package for a custom build and it works fine.

**Comment by aparcar** [comment]
Yes there was a problem with the path, should be fixed

**Comment by maurice-w** [comment]
Firmware selector does indeed work for me, but still no luck with `luci-app-attendedsysupgrade`. Am I missing something?

![image](https://github.com/user-attachments/assets/afa26c8f-8349-42a7-b14d-75fd35ebefa7)

**Comment by fsa** [comment]
It's likely that you've already requested the build you need before.  For such assemblies, 404 is still issued. I had to change one package on the site and then I got a working firmware.  And through luci it also gives an error.

**Comment by maurice-w** [comment]
Never mind, I found #896. It works with `auc`.

**Comment by udanfacy22** [comment]
Neither `auc` nor `luci-app-attendedsysupgrade` work for me. I'm using a Raspberry Pi 4B (64-bit) that is currently running OpenWrt 23.05.3.

luci-app-attendedsysupgrade gives me the same `{"detail":"Not Found"}` error that others mentioned.

`auc` gives me this output:

`auc/0.3.2-1
Server:    https://sysupgrade.openwrt.org
Running:   23.05.3 r23809-234f1a2efa on bcm27xx/bcm2711 (raspberrypi,4-model-b)
Invalid argument (22)`

Fortunately, using the firmware-selector, I was able to successfully build 23.05.4 with custom packages.

**Comment by aparcar** [comment]
Thanks for testing and feedback, I'll try to give this another go tonight

**Comment by devastgh** [comment]
As of now, `auc` upgrading to 23.05.4 doesn't work on my x86/64 devices. Luci app same story.

```
root@HAWAII:~# auc -c
auc/0.3.2-1
Server:    https://sysupgrade.openwrt.org/
Running:   23.05.3 r23809-234f1a2efa on x86/64 (generic)
No data available (61)
```

**Comment by udanfacy22** [comment]
`auc -c` isn't working on my Raspberry Pi 4 running OpenWrt 23.05.3.

    auc/0.3.2-1
    Server:    https://sysupgrade.openwrt.org
    Running:   23.05.3 r23809-234f1a2efa on bcm27xx/bcm2711 (raspberrypi,4-model-b)
    Invalid argument (22)

`luci-app-attended-sysupgrade`, however, was successful.

**Comment by aparcar** [comment]
@devastgh i can't reproduce the issue

**Comment by devastgh** [comment]
> @devastgh i can't reproduce the issue

I upgraded my x86/64 boxes manually from firmware selector, however auc still fails there even on 23.05.4:

```
root@HAWAII:~# auc -c
auc/0.3.2-1
Server:    https://sysupgrade.openwrt.org/
Running:   23.05.4 r24012-d8dd03c46f on x86/64 (generic)
No data available (61)

root@PENTAGON:~# auc -c
auc/0.3.2-1
Server:    https://sysupgrade.openwrt.org/
Running:   23.05.4 r24012-d8dd03c46f on x86/64 (generic)
No data available (61)
``` 

Both devices are dual stack, so connection is probably ipv6 to the servers.

My ipv4 only AX3000T devices work properly:

```
root@Bahamas:~# auc -c
auc/0.3.2-1
Server:    https://sysupgrade.openwrt.org
Running:   23.05.4 r24012-d8dd03c46f on mediatek/filogic (xiaomi,mi-router-ax3000t)
Available: 23.05.4 r24012-d8dd03c46f
Requesting package lists...
 luci-mod-network: git-24.111.76511-ff6b275 -> git-24.207.52553-1f36628
``` 

I have absolutely no clue what the issue could be here.

**Comment by devastgh** [comment]
> I have absolutely no clue what the issue could be here.

Found the issue. I had `https://sysupgrade.openwrt.org/` in the config instead of `https://sysupgrade.openwrt.org` . It doesn't like the trailing slash in the url. Sorry for the confusion there.

**Comment by lpic10** [comment]
> Found the issue. I had `https://sysupgrade.openwrt.org/` in the config instead of `https://sysupgrade.openwrt.org` . It doesn't like the trailing slash in the url. Sorry for the confusion there.

It's been weeks I'm trying the update and that did the trick.

Something has changed on server side that is causing this issue as I never changed the config, so I believe that was coming as default (at least on previous builds). 

I think it would be better to find a solution server side, as a lot of other users may not find this info here.

**Comment by aparcar** [comment]
> I think it would be better to find a solution server side, as a lot of other users may not find this info here.

Should be fixed via https://github.com/openwrt/asu/pull/936

**Comment by hainguyen-cmd** [comment]
Is there any problem? I have tried to customize firmware with selected packages through https://firmware-selector.openwrt.org but can not! The error is: 

index.js:118 
        
        
       POST https://sysupgrade.openwrt.org/api/v1/build net::ERR_ABORTED 502 (Bad Gateway)

Thanks.
